9 Создать страницу редактирования данных пользователя
kimfromsiberia/sports_social_network pull request #15
Opened 2024-04-04 15:59 UTC by kimfromsiberia

Редактирование:
имя
фамилия
дата рождения
страна
город

2024-04-05 11:19 UTC, lwof requested changes
Ты на правильном пути, пара мелких исправлений только.

2024-04-05 11:19 UTC, lwof commented on sport_social_network/templates/user_settings.html
> +        <input name="date_of_birth" class="form-control" value="{{ user.date_of_birth.strftime('%d.%m.%Y') }}">
Вот здесь падает, если date_of_birth у юзера None, а оно None, сразу после создания пользователя. 
Надо учесть случай None

2024-04-05 11:19 UTC, lwof commented on sport_social_network/templates/user_settings.html
> +        <input name="last_name" class="form-control" value="{{ user.last_name }}">
И для остальных полей по хорошему сделать бы обработку None,  что бы не пугать ими пользователя.

2024-04-05 11:19 UTC, lwof commented on sport_social_network/__init__.py
> +            try:
вот тут хорошо получилось, ошибка в дате (весьма вероятная) не ломает флоу сохранения других параметров 👍

2024-04-05 11:19 UTC, lwof commented on sport_social_network/__init__.py
> +            db.session.add(user)
Насколько я помню, если изменяешь ранее подгруженный через ORM объект, то даже не надо делать add

2024-04-06 12:59 UTC, lwof requested changes

2024-04-06 12:59 UTC, lwof commented on sport_social_network/templates/user_settings.html
> +        <input name="date_of_birth" class="form-control" value="{{ user.date_of_birth.strftime('%d.%m.%Y') }}">
Вот тут не вижу что бы это было пофикшено. Можешь написать как решил эту проблему?

2024-04-06 13:17 UTC, kimfromsiberia commented on sport_social_network/templates/user_settings.html
> +        <input name="date_of_birth" class="form-control" value="{{ user.date_of_birth.strftime('%d.%m.%Y') }}">
В шаблоне user_settings добавил проверку для каждого поля ввода. Если есть что-то в базе, то выводить. Если нет, то пустая строка вместо None.
        {% if user.date_of_birth %}
        <input name="date_of_birth" class="form-control" value="{{ user.date_of_birth.strftime('%d.%m.%Y') }}">
        <label>Дата рождения в формате день.месяц.год</label>
        {% else %}
        <input name="date_of_birth" class="form-control">
        <label>Дата рождения в формате день.месяц.год</label>
        {% endif %}

2024-04-07 03:45 UTC, merged