Model experiments
kimfromsiberia/sports_social_network pull request #19
Opened 2024-04-09 05:06 UTC by kimfromsiberia

2024-04-09 15:09 UTC, lwof requested changes

2024-04-09 15:09 UTC, lwof commented on sport_social_network/__init__.py
> +            user = SportObject.query.filter(SportObject.id == current_user.id).first()
Я бы предложил назвать эту переменную здесь и выше по разному. Соответсвенно как profile и sports_object. 
Потому что когда у тебя в одном и том же имени переменной могут лежать разные значения код значительно сложнее понимать. Плюс это ломает инструменты, которые могли бы дать тебе варнинг о том что ты например к какому-то не тому атрибуту обращаешься.

2024-04-09 15:09 UTC, lwof commented on sport_social_network/__init__.py
> +                            new_user = SportObject(email=email, password=password, user_type='sport_object')
Я думал что email и пароль останутся в таблице User. Как раз что бы все в одном месте было. Может все же перенесем их в таблицу User? И из Person тоже убрать я имею в виду.

2024-04-09 15:09 UTC, lwof commented on sport_social_network/__init__.py
> +                            new_user = SportObject(email=email, password=password, user_type='sport_object')
В этом случае у тебя будет только один вариант кода аутентификации.

2024-04-09 15:37 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +                            new_user = SportObject(email=email, password=password, user_type='sport_object')
Они и остались в User. Я к password и email обращаюсь через Person и SpotrObject, чтобы сразу создать запись в таблице Person и User с одинаковым id

2024-04-09 15:37 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +            user = SportObject.query.filter(SportObject.id == current_user.id).first()
да, переделаю

2024-04-12 16:27 UTC, lwof approved these changes

2024-04-15 07:13 UTC, closed without merging