12 add flask wtf
kimfromsiberia/sports_social_network pull request #21
Opened 2024-04-17 06:14 UTC by kimfromsiberia

Добавил flask_wtf.
Если пользователь аутентифицирован при переходе на страницу входа, направлять его на страницу пользователя.

2024-04-19 06:28 UTC, lwof requested changes
Пара мелких замечаний.

2024-04-19 06:28 UTC, lwof commented on sport_social_network/__init__.py
> +                    if form.password.data and form.confirm_password.data:
Если ты указал в форме пароли как обязательные поля (а их следовало так указать), то тут можно повторно не проверять наличие data.
Это уже было проверено когда ты проверял `if form.validate_on_submit`

2024-04-19 06:28 UTC, lwof commented on sport_social_network/__init__.py
> +                    if form.password.data and form.confirm_password.data:
Аналогично

2024-04-19 06:28 UTC, lwof commented on sport_social_network/__init__.py
> +            if form.is_submitted():
`validate_on_submit` мне кажется предпочтительнее. И точно лучше везде использовать одинаковый метод.

2024-04-19 06:28 UTC, lwof commented on sport_social_network/__init__.py
> +            if form.is_submitted():
Аналогично

2024-04-20 18:24 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +            if form.is_submitted():
Сделал

2024-04-20 18:24 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +            if form.is_submitted():
Ок

2024-04-20 18:24 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +                    if form.password.data and form.confirm_password.data:
И тут

2024-04-20 18:25 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +                    if form.password.data and form.confirm_password.data:
Тут переделаю

2024-04-22 16:10 UTC, lwof approved these changes
LGTM

2024-04-23 00:59 UTC, merged