Feature/6 implement user login and registration
kimfromsiberia/sports_social_network pull request #8
Opened 2024-03-26 17:21 UTC by kimfromsiberia

регистрация пользователя на сайте
вход пользователя и редирект на страницу пользователя

2024-03-26 20:09 UTC, lwof requested changes

2024-03-26 20:09 UTC, lwof commented on sport_social_network/__init__.py
> +        if current_user.is_authenticated:
хм, я бы возможно предложил в будущем скорее использовать декоратор `@login_required`, что бы разделять что мы показываем без логина. 

То есть тут же логика такая, что если пользователь залогинен мы показываем ему его личную страничку, а если нет, то надо редиректить на страницу регистрации. Правильно я понял?

Если так, то это как раз делается с @login_required + плюс указать какая вьюха используется для логина/регистрации.  (Это уже сделано через `login_manager.login_view`)

2024-03-27 15:26 UTC, kimfromsiberia commented on sport_social_network/__init__.py
> +        if current_user.is_authenticated:
Тогда я пока удалю эти две строчки. А в следующих тасках сделаю через login_required

2024-03-30 20:59 UTC, lwof approved these changes
LGTM

2024-03-31 05:38 UTC, merged